---
title: "Arabidopsis copula"
output: html_document
date: "2026-07-23"
editor_options: 
  chunk_output_type: console
---
#////////////////////////////////////////////////////

#Arabidopsis - Sartori et al., 2019

```{r}
data <- read_delim("data/Data_Slow-fast-LES_Arabidopsis_thaliana.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE) %>%dplyr::select(ecotype_id, LMA, LMAPlant, Amass, AmassPlant, LLS)

length(unique(data$ecotype_id)) #378

# Verify NA
traits_list <- list(
  LMA    = data$LMA,
  Amass  = data$Amass,
  LLS     = data$LLS,
  LMAPlant = data$LMAPlant,
  AmassPlant = data$AmassPlant)

pairs <- combn(names(traits_list), 2, simplify = FALSE)

n_table <- do.call(rbind, lapply(pairs, function(p) {
  df <- na.omit(data.frame(
    x = traits_list[[p[1]]],
    y = traits_list[[p[2]]]))
  data.frame(pair = paste(p[1], p[2], sep="–"), n = nrow(df))
})) %>% arrange(n) 

print(n_table)

# LMA–Amass 317
#  LMAPlant–AmassPlant 284
# Amass–LLS 236
# LMA–LLS 260
```

# LMA–Amass 

n=317

```{r}
lma <- data$LMA
a <- data$Amass

plot(lma, a)

cor(lma, a, method ='spearman', use= "pairwise.complete.obs") 

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = lma, Y = a))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
# Pour une relation négative, utiliser les rotations 
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) #If TRUE, all rotations of the families in familyset are included (or subtracted). that's why we see a difference between asked and selected
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, #lower tail dependance 'TD'
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) #upper tail dependance 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE will pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.1, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.1, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif


# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réelle : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionnelles sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_Amass_ITV <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "Amass",
       subtitle = paste0("Student t")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_Amass_ITV
```

# LMAPlant–AmassPlant 
n=284

```{r}
lma <- data$LMAPlant
a <- data$AmassPlant

plot(lma, a)

cor(lma, a, method ='spearman', use= "pairwise.complete.obs") 

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = lma, Y = a))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
# Pour une relation négative, utiliser les rotations 
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) #If TRUE, all rotations of the families in familyset are included (or subtracted). that's why we see a difference between asked and selected
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, #lower tail dependance 'TD'
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) #upper tail dependance 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE will pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif


# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réelle : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionnelles sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_Amass_ITV_Plant <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA Plant",
       y     = "Amass Plant",
       subtitle = paste0("Student t")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_Amass_ITV_Plant
```


# LMA–LL 

n=260

```{r}
lma <- data$LMA
ll <- data$LLS

plot(lma, ll)

cor(lma, ll, method ='spearman', use= "pairwise.complete.obs") 

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = lma, Y = ll))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
# Pour une relation négative, utiliser les rotations 
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) #If TRUE, all rotations of the families in familyset are included (or subtracted). that's why we see a difference between asked and selected
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, #lower tail dependance 'TD'
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) #upper tail dependance 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE will pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.1, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.1, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif


# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réelle : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionnelles sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_LL_ITV <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "LL",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_LL_ITV
```

# Amass–LLS 
n=236

```{r}
a <- data$Amass
ll <- data$LLS

plot(a, ll)

cor(a, ll, method ='spearman', use= "pairwise.complete.obs") 

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = a, Y = ll))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
# Pour une relation négative, utiliser les rotations 
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) #If TRUE, all rotations of the families in familyset are included (or subtracted). that's why we see a difference between asked and selected
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, #lower tail dependance 'TD'
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) #upper tail dependance 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE will pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif


# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réelle : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionnelles sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_A_LL_ITV <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "A",
       y     = "LL",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_A_LL_ITV
```

#PLOT- Figure 2
```{r}
LMA <- ggarrange(plot_LMA_Amass_ITV,  plot_LMA_LL_ITV, ncol = 1, common.legend = T, legend = "none")

Amass<- ggarrange(NULL, plot_A_LL_ITV, ncol = 1, common.legend = T, legend = "none")

figure2A <- ggarrange(LMA, Amass, nrow = 1, ncol=2)
figure2B <- plot_LMA_Amass_ITV_Plant

figure2 <- ggarrange(figure2A, figure2B)
```

#////////////////////////////////////////////////////
#Arabido mean traits
```{r}

data <- read_delim("data/arabido mean traits.csv",
    delim = ";",
    locale = locale(decimal_mark = ","),
    escape_double = FALSE, trim_ws = TRUE)

length(unique(data$genotypeID)) #721

# Verify NA
traits_list <- list(
  LMA    = data$LMA,
  Nmass  = data$Nmass,
  LA     = data$leaf_area,
  biomass = data$biomass,
  SM = data$seed_mass,
  SSD= data$Stem_density)

pairs <- combn(names(traits_list), 2, simplify = FALSE)

n_table <- do.call(rbind, lapply(pairs, function(p) {
  df <- na.omit(data.frame(
    x = traits_list[[p[1]]],
    y = traits_list[[p[2]]]))
  data.frame(pair = paste(p[1], p[2], sep="–"), n = nrow(df))
})) %>% arrange(n) 

print(n_table)

#spearman 
data <- data%>%
  rename(LA= leaf_area, 
         SM=seed_mass,
        SSD=Stem_density)%>%
  mutate(biomass=as.numeric(biomass),
         SM= as.numeric(SM),
         SSD=as.numeric(SSD))

traits <- data[, c("LMA", "Nmass", "LA", "SM", "biomass", "SSD")]

# Pairwise Spearman correlation matrix
cor_matrix <- cor(traits, method = "spearman", use = "pairwise.complete.obs")
print(round(cor_matrix, 3))
```

#LMA - Nmass

```{r}
lma <- data$LMA
ln <- data$Nmass

plot(lma, ln)

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
#problem with NA
df <- na.omit(data.frame(X = lma, Y = ln))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
# Pour une relation négative, utiliser les rotations 
families <- c(1,2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) #If TRUE, all rotations of the families in familyset are included (or subtracted). that's why we see a difference between asked and selected
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, #lower tail dependance 'TD'
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) #upper tail dependance 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset = families, rotations = T, presel = F)  #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.1, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.1, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif

# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réeHe : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionneHes sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_Nmass <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "Nmass",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0(" Rotated Gumbel 90 degrees")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(), 
        axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_Nmass
```

#LMA - LA
```{r}
lma <- data$LMA
la <- data$LA

plot(lma, la)

cor(lma, la, method ='spearman', use= "pairwise.complete.obs") #-0.72

df <- na.omit(data.frame(X = lma, Y = la))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
families <- c(1, 2,3,4,5,6)

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset = families, rotations = T, presel = F) 
selectedCopula
summary(selectedCopula)

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.9, 0.1, selectedCopula)  
BiCopPDF(0.1, 0.9, selectedCopula) 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_LA <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alaha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "LA",
       title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Survival Gumbel")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())

plot_LMA_LA
```


#LMA - SM
```{r}
lma <- data$LMA
sm <- data$SM

plot(lma, sm)

cor(lma, sm, method ='spearman', use= "pairwise.complete.obs") 

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = lma, Y = sm))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles (relation négative --> 0.1/0.9)
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 
# comme le premier > le second → couplage plus fort au pôle conservatif


# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réeHe : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionneHes sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_SM <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "SM",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_SM
```

#LMA-Biomass
```{r}
lma <- data$LMA
H <- data$biomass

plot(lma, H)

cor(lma, H, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = lma, Y = H))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle acquisitif because lma
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle conservatif beacause lma
# comme le premier > le second → couplage plus fort au pôle conservatif

# La densité copule se lit par rapport à 1 : une valeur de 3.06 signifie que la co-occurrence (bas SLA, bas N) est 3× plus probable que si les deux traits étaient indépendants. Une valeur de 1.59 signifie 1.6× plus probable. Une asymétrie réeHe : densité ~3× au pôle conservatif vs ~1.6× au pôle acquisitif — les contraintes fonctionneHes sont plus serrées pour les faibles valeurs

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_H <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "Biomass",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Gaussian")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_H
```

#LMA-SSD
```{r}
lma <- data$LMA
ssd <- data$SSD

plot(lma, ssd)

cor(lma, ssd, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
u<- pobs(as.matrix(cbind(lma, ssd)))[,1] 
v<- pobs(as.matrix(cbind(lma, ssd)))[,2]

#but actually probelem with NA
#problem with NA has to be delt like that:
df <- na.omit(data.frame(X = lma, Y = ssd))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # pôle conservateur (LMA haut, Rdmass bas)
BiCopPDF(0.9, 0.9, selectedCopula)  # pôle acquisitif   (LMA bas, Rdmass haut)
# comme le premier > le second → couplage plus fort au pôle conservatif

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LMA_SSD <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LMA",
       y     = "SSD",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("t")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LMA_SSD
```



#Nmass-LA
```{r}
Nmass <- data$Nmass
la <- data$LA

plot(Nmass, la)

cor(Nmass, la, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
#pseudo observations are the observations in the [0,1] interval
df <- na.omit(data.frame(X = Nmass, Y = la))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservateur
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle aquisitif

#Plot
#grid construction
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_Nmass_LA <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alaha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "Nmass",
       y     = "LA",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Rotated Clayton 90 degrees")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_Nmass_LA
```

#Nmass-SM
```{r}
Nmass <- data$Nmass
sm <- data$SM

plot(Nmass, sm)

cor(Nmass, sm, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
df <- na.omit(data.frame(X = Nmass, Y = sm))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_Nmass_SM <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "Nmass",
       y     = "SM",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Rotated Clayton 270°")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_Nmass_SM
```

#Nmass-biomass
```{r}
Nmass <- data$Nmass
H <- data$biomass

plot(Nmass,H)

cor(Nmass, H, method ='spearman', use= "pairwise.complete.obs")

#problem with NA
df <- na.omit(data.frame(X = Nmass, Y = H))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.9, 0.1, selectedCopula)  # densité au pôle acquisitif
BiCopPDF(0.1, 0.9, selectedCopula)  # densité au pôle conservatif

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_Nmass_H <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "Nmass",
       y     = "Biomass",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_Nmass_H
```

#Nmass-SSD
```{r}
Nmass <- data$Nmass
ssd <- data$SSD 

plot(Nmass,ssd)

cor(Nmass, ssd, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
df <- na.omit(data.frame(X = Nmass, Y = ssd))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.9, 0.1, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.1, 0.9, selectedCopula)  # densité au pôle conservatif

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_Nmass_SSD <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "Nmass",
       y     = "SSD",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_Nmass_SSD
```


#LA-SM
```{r}
LA <- data$LA
sm <- data$SM 

plot(LA, sm)

cor(LA, sm, method ='spearman', use= "pairwise.complete.obs")

#problem with NA
df <- na.omit(data.frame(X = LA, Y = sm))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]


#Select copula
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) 
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, 
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family #34 rotated Gumbel copula (270 degrees)
selectedCopula$tau #dépendance négative globale (tau = -0.47)
selectedCopula$par #-1.91 controls overall dependance sterngth must be >= 1 ??
selectedCopula$par2 #0 controls asymettry entre 0 et 1 

# Densités aux pôles
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LA_SM <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LA",
       y     = "SM",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Frank")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LA_SM
```


#LA-Biomass
```{r}
LA <- data$LA
H <- data$biomass 

plot(LA, H)

cor(LA, H, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
u<- pobs(as.matrix(cbind(LA, H)))[,1] 
v<- pobs(as.matrix(cbind(LA, H)))[,2]

#problem with NA
df <- na.omit(data.frame(X = LA, Y = H))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family 
selectedCopula$tau 
selectedCopula$par 
selectedCopula$par2

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LA_H <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LA",
       y     = "Biomass",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Clayton")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LA_H
```

#LA-SSD
```{r}
LA <- data$LA
ssd <- data$SSD 

plot(LA, ssd)

cor(LA, ssd, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
#problem with NA
df <- na.omit(data.frame(X = LA, Y =ssd))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) 
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, 
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family 
selectedCopula$tau 
selectedCopula$par 
selectedCopula$par2 

# Densités aux pôles
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_LA_SSD <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "LA",
       y     = "SSD",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Clayton")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_LA_SSD
```



#SM-biomass
```{r}
SM <- data$SM
H <- data$biomass

plot(SM, H)

cor(SM, H, method ='spearman', use= "pairwise.complete.obs")

#problem with NA
df <- na.omit(data.frame(X = SM, Y = H))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family 
selectedCopula$tau 
selectedCopula$par 
selectedCopula$par2

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_SM_H <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "SM",
       y     = "Biomass",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("t")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(),
           axis.text.x = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_SM_H
```

#SM-SSD
```{r}
SM <- data$SM
ssd <- data$SSD 

plot(SM, ssd)

cor(SM, ssd, method ='spearman', use= "pairwise.complete.obs")

#transform in ranks, using pseudo observations 
df <- na.omit(data.frame(X = SM, Y = ssd))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family 
selectedCopula$tau 
selectedCopula$par 
selectedCopula$par2

# Densités aux pôles
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle acquisitif 
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle conservatif 

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_SM_SSD <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "SM",
       y     = "SSD",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("Survival Clayton")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_SM_SSD
```



#Biomass-SSD
```{r}
H <- data$biomass
ssd <- data$SSD 

plot(H, ssd)

cor(H, ssd, method ='spearman', use= "pairwise.complete.obs")

#problem with NA
df <- na.omit(data.frame(X = H, Y = ssd))
uv <- pobs(as.matrix(df))
u  <- uv[,1]
v  <- uv[,2]

#Select copula
families <- c(1, 2,3,4,5,6)

#fit one by one to see the different AIC per copulas
results <- lapply(families, function(f) {
  fit <- BiCopSelect(u, v, familyset = f, rotations = T) 
  data.frame(family_asked = f,
             family_selected = fit$family,
             family_name= fit$familyname,
             BIC = fit$BIC,
             AIC = fit$AIC, 
             tau = fit$tau,
             par1= fit$par,
             par2 = fit$par2,
             lower_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$lower, 
             upper_TD = BiCopPar2TailDep(fit$family, fit$par, fit$par2)$upper) 
})

all_result <- do.call(rbind, results)

all_result %>% mutate(across(where(is.numeric) & !c(family_asked, family_selected),
                ~ round(.x, 3)))%>%
  distinct(family_name, .keep_all=T)%>%
  arrange(desc(AIC))

#Best Copula
selectedCopula <- BiCopSelect(u, v, familyset =families, rotations = T, presel = F) #presel if TRUE wiH pre-select copulas to compare for a faster result. essential to set it to false to test all the families in familyset.
selectedCopula
summary(selectedCopula)

selectedCopula$family 
selectedCopula$tau 
selectedCopula$par 
selectedCopula$par2

# Densités aux pôles
BiCopPDF(0.1, 0.1, selectedCopula)  # densité au pôle acquisitif
BiCopPDF(0.9, 0.9, selectedCopula)  # densité au pôle conservatif

#Plot
u_seq <- seq(0.01, 0.99, length.out = 50)
v_seq <- seq(0.01, 0.99, length.out = 50)
grid  <- expand.grid(u = u_seq, v = v_seq)
grid$density <- BiCopPDF(grid$u, grid$v, selectedCopula)

plot_H_SSD <- ggplot(grid, aes(x = u, y = v, fill = density)) +
  geom_tile() +
  geom_contour(aes(z = density), color = "white", 
               alpha = 0.6, linewidth = 0.4) +
  scale_fill_gradientn(
     colours = c("white", "#aad576", "#73a942", "#245501", 
                "#1a4301"),
    name    = "Density") +
  labs(x     = "Biomass",
       y     = "SSD",
        title= "Arabidopsis 703 genotypes",
       subtitle = paste0("t")) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank())
#useful add aspect.ratio =1 to theme for 1:1 plot
plot_H_SSD
```


#PLOT- Figure 
```{r}
LMA <- ggarrange(plot_LMA_Nmass,  plot_LMA_LA, plot_LMA_SM,  plot_LMA_H, plot_LMA_SSD, ncol = 1, common.legend = T, legend = "none")

Nmass <- ggarrange( NULL, plot_Nmass_LA, plot_Nmass_SM,  plot_Nmass_H, plot_Nmass_SSD, ncol = 1, common.legend = T, legend = "none")

LA <- ggarrange( NULL,  NULL, plot_LA_SM,  plot_LA_H, plot_LA_SSD, ncol = 1, common.legend = T, legend = "none")

SM<- ggarrange(NULL, NULL,  NULL, plot_SM_H, plot_SM_SSD, ncol = 1, common.legend = T, legend = "none")

H<- ggarrange(NULL, NULL,  NULL, NULL, plot_H_SSD, ncol = 1, common.legend = T, legend = "none")

figure <- ggarrange(LMA, Nmass, LA, SM, H, nrow = 1)
figure
```
